<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/08/05 11:56:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=eevar',
  'username' => 'root',
  'password' => 'uc5aajak',
  'name' => 'doctrine',
)),);
