<?php

/**
 * BaseCasestudy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $case_name
 * @property Doctrine_Collection $Case
 * 
 * @method string              getCaseName()  Returns the current record's "case_name" value
 * @method Doctrine_Collection getCase()      Returns the current record's "Case" collection
 * @method Casestudy           setCaseName()  Sets the current record's "case_name" value
 * @method Casestudy           setCase()      Sets the current record's "Case" collection
 * 
 * @package    eVar
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCasestudy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('casestudy');
        $this->hasColumn('case_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Experts as Case', array(
             'local' => 'id',
             'foreign' => 'casestudy_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}