<?php

/**
 * BaseExperts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $expert_name
 * @property string $username
 * @property string $password
 * @property integer $casestudy_id
 * @property Casestudy $Casestudy
 * @property Doctrine_Collection $Expert
 * 
 * @method string              getExpertName()   Returns the current record's "expert_name" value
 * @method string              getUsername()     Returns the current record's "username" value
 * @method string              getPassword()     Returns the current record's "password" value
 * @method integer             getCasestudyId()  Returns the current record's "casestudy_id" value
 * @method Casestudy           getCasestudy()    Returns the current record's "Casestudy" value
 * @method Doctrine_Collection getExpert()       Returns the current record's "Expert" collection
 * @method Experts             setExpertName()   Sets the current record's "expert_name" value
 * @method Experts             setUsername()     Sets the current record's "username" value
 * @method Experts             setPassword()     Sets the current record's "password" value
 * @method Experts             setCasestudyId()  Sets the current record's "casestudy_id" value
 * @method Experts             setCasestudy()    Sets the current record's "Casestudy" value
 * @method Experts             setExpert()       Sets the current record's "Expert" collection
 * 
 * @package    eVar
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExperts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('experts');
        $this->hasColumn('expert_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('casestudy_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Casestudy', array(
             'local' => 'casestudy_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('EQs as Expert', array(
             'local' => 'id',
             'foreign' => 'expert_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}