<?php

/**
 * BaseLags
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $lag_one
 * @property decimal $lag_two
 * @property decimal $lag_three
 * @property decimal $lag_four
 * @property decimal $lag_five
 * @property decimal $lag_six
 * @property decimal $lag_seven
 * @property integer $casestudy_id
 * @property Casestudy $Casestudy
 * 
 * @method decimal   getLagOne()       Returns the current record's "lag_one" value
 * @method decimal   getLagTwo()       Returns the current record's "lag_two" value
 * @method decimal   getLagThree()     Returns the current record's "lag_three" value
 * @method decimal   getLagFour()      Returns the current record's "lag_four" value
 * @method decimal   getLagFive()      Returns the current record's "lag_five" value
 * @method decimal   getLagSix()       Returns the current record's "lag_six" value
 * @method decimal   getLagSeven()     Returns the current record's "lag_seven" value
 * @method integer   getCasestudyId()  Returns the current record's "casestudy_id" value
 * @method Casestudy getCasestudy()    Returns the current record's "Casestudy" value
 * @method Lags      setLagOne()       Sets the current record's "lag_one" value
 * @method Lags      setLagTwo()       Sets the current record's "lag_two" value
 * @method Lags      setLagThree()     Sets the current record's "lag_three" value
 * @method Lags      setLagFour()      Sets the current record's "lag_four" value
 * @method Lags      setLagFive()      Sets the current record's "lag_five" value
 * @method Lags      setLagSix()       Sets the current record's "lag_six" value
 * @method Lags      setLagSeven()     Sets the current record's "lag_seven" value
 * @method Lags      setCasestudyId()  Sets the current record's "casestudy_id" value
 * @method Lags      setCasestudy()    Sets the current record's "Casestudy" value
 * 
 * @package    eVar
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLags extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lags');
        $this->hasColumn('lag_one', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('lag_two', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('lag_three', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('lag_four', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('lag_five', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('lag_six', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('lag_seven', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('casestudy_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Casestudy', array(
             'local' => 'casestudy_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}