<?php

/**
 * BasePmpdf
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property decimal $max
 * @property decimal $min
 * @property string $dist_name
 * @property decimal $mean
 * @property decimal $std
 * @property decimal $lsq
 * @property decimal $N_exp
 * @property decimal $fQ
 * @property decimal $tQ
 * @property integer $casestudy_id
 * @property Casestudy $Casestudy
 * 
 * @method decimal   getMax()          Returns the current record's "max" value
 * @method decimal   getMin()          Returns the current record's "min" value
 * @method string    getDistName()     Returns the current record's "dist_name" value
 * @method decimal   getMean()         Returns the current record's "mean" value
 * @method decimal   getStd()          Returns the current record's "std" value
 * @method decimal   getLsq()          Returns the current record's "lsq" value
 * @method decimal   getNExp()         Returns the current record's "N_exp" value
 * @method decimal   getFQ()           Returns the current record's "fQ" value
 * @method decimal   getTQ()           Returns the current record's "tQ" value
 * @method integer   getCasestudyId()  Returns the current record's "casestudy_id" value
 * @method Casestudy getCasestudy()    Returns the current record's "Casestudy" value
 * @method Pmpdf     setMax()          Sets the current record's "max" value
 * @method Pmpdf     setMin()          Sets the current record's "min" value
 * @method Pmpdf     setDistName()     Sets the current record's "dist_name" value
 * @method Pmpdf     setMean()         Sets the current record's "mean" value
 * @method Pmpdf     setStd()          Sets the current record's "std" value
 * @method Pmpdf     setLsq()          Sets the current record's "lsq" value
 * @method Pmpdf     setNExp()         Sets the current record's "N_exp" value
 * @method Pmpdf     setFQ()           Sets the current record's "fQ" value
 * @method Pmpdf     setTQ()           Sets the current record's "tQ" value
 * @method Pmpdf     setCasestudyId()  Sets the current record's "casestudy_id" value
 * @method Pmpdf     setCasestudy()    Sets the current record's "Casestudy" value
 * 
 * @package    eVar
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePmpdf extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pmpdf');
        $this->hasColumn('max', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('min', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('dist_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('mean', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('std', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('lsq', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('N_exp', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('fQ', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('tQ', 'decimal', 20, array(
             'type' => 'decimal',
             'scale' => 3,
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('casestudy_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Casestudy', array(
             'local' => 'casestudy_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}