<?php

/**
 * CasestudyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CasestudyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CasestudyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Casestudy');
    }
}