<?php

/**
 * LagsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LagsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LagsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Lags');
    }
}