<?php

/**
 * PmpdfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PmpdfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PmpdfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pmpdf');
    }
}