<?php

/**
 * PoolvariogramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PoolvariogramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PoolvariogramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Poolvariogram');
    }
}